### ISSUE TITLE
Can I somehow only retrieve messages from certain users? 

### ISSUE THREAD

**Issue by pascal-mueller** [Dracovian/Discord-Scraper#67]
Hello,

Can I somehow provide a list of users I want to get the new messages from? Or maybe even roles?

As far as I have seen, that's not supported but maybe I just didn't see it.

Edit: I'm currently trying to implement it on my own. For that, I just added a `author_id` field to the config and added it to the parameters array. So it generates something like this:

`discord.com/api/v8/channels/<server_id>/messages/search?min_id=837448158412800000&max_id=837810542084096000&author_id=<author_id>&include_nsfw=true.`

whereas the web application makes this call
`discord.com/api/v9/guilds/<server_id>/messages/search?author_id=849859808127746118`

Do you knwo if I can somehow use `author_id` with the first kind of URI?

**Comment by Dracovian** [comment]
So far the script doesn't provide any built-in method of doing this, the script's interest is mostly in channel-wide scraping as a means of archival.

Of course it wouldn't be difficult to implement something like this with the given code since you only have to add the following to DiscordScraper.py file in the modules subfolder on line 195:

```py
author_id = '<author_id>',
```

And that should work to my recollection.

**Comment by pascal-mueller** [comment]
> So far the script doesn't provide any built-in method of doing this, the script's interest is mostly in channel-wide scraping as a means of archival.
> 
> Of course it wouldn't be difficult to implement something like this with the given code since you only have to add the following to DiscordScraper.py file in the modules subfolder on line 195:
> 
> ```python
> author_id = '<author_id>',
> ```
> 
> And that should work to my recollection.

I

**Comment by pascal-mueller** [comment]
> So far the script doesn't provide any built-in method of doing this, the script's interest is mostly in channel-wide scraping as a means of archival.
> 
> Of course it wouldn't be difficult to implement something like this with the given code since you only have to add the following to DiscordScraper.py file in the modules subfolder on line 195:
> 
> ```python
> author_id = '<author_id>',
> ```
> 
> And that should work to my recollection.

shit didn't want to close. haha, yeah I think you have to trick a bit if you want to get a message by id if you aren't a bot. :) My myself a simple script. Thanks though.
