### ISSUE TITLE
Blank folders, urllib2 error

### ISSUE THREAD

**Issue by markman641** [Dracovian/Discord-Scraper#8]
Outdated

So I was able to successfully find my token by going to Network, refreshing the page, filtering by "/api", clicking on "access-token", headers, then copied where it says authorization:

The script seems to run now. It creates the folders with the server & channel names.
However, there is nothing inside the folders. They are completely empty.

I looked further into the code and it looks like there is an error on line 86, 
`    from urllib2 import build_opener, install_opener, urlopen, HTTPError `
This seems like it is because Python 3 doesn't have "urllib2", only urllib with different modules.

Also, the messages I am scraping are only text, no images or anything

I am not a Python developer so I'm lost at this point.. any ideas

**Comment by markman641** [comment]
I printed contents after line 171 and this is what prints: 

> {'total_results': 0, 'analytics_id': 'e5fd73850d6d8537dad41d0394aa0dc8', 'messages': []}
{'total_results': 0, 'analytics_id': '65738db80087236dc15e52809947b5a2', 'messages': []}

I'm assuming this just means its not finding the message for some reason...

**Comment by Dracovian** [comment]
The use of sys.version determines whether the script will use http.client (Python 3) or urllib2 (Python 2) so that this script can run on both of those versions of Python.

I still need to make an update to this script to fix the issues with the authorization token not being in the same place anymore and fix some issues with the scraping.

**Comment by markman641** [comment]
Please let me know when this is updated! I'm just trying to scrape text from a few discord text channels every few minutes then using that text to run another script. I've made some heavy modifications to the code and i'm able to pull the text now in a json format so i seem to be ok for now

**Comment by Dracovian** [comment]
The script has been updated and I've retained cross-compatibility support among Python 2 and Python 3 users while updating the readme to show the new method of gathering the authorization token. Please open up a new issue if this problem persists or if another problem arises.

I thank you for contributing to this project!
